config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  resources :categories

  resources :products do
    member do
      post :buy
      post :cancel
    end
  end

  resources :carts do
    member do
      get  :show_address
      post :update_address
      get  :show_payment
      post :update_payment
    end
  end

  resources :orders do
    member do
      get :thank_you
      get :show_acceptance
      post :update_acceptance
    end
  end

  Bemine::Application.routes.draw do
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  validates_presence_of :name, :amount
  validate :has_line_item, on: [:create, :update]

  belongs_to :user
  belongs_to :fulfiller, class_name: 'User', foreign_key: 'fulfiller_id'

  has_one :line_item
  has_one :shipping_address, class_name: 'Address', as: :addressable
  has_many :fulfill_requests

  accepts_nested_attributes_for :shipping_address, allow_destroy: true, reject_if: :all_blank

  store :transaction_info, accessors: [:bt_transaction_id]

  def accepted?
    !fulfiller_id.nil?
  end

  def has_line_item
    errors.add(:order, 'has no line_item') if line_item.nil?
  end

  def self.build_from_cart(cart, user)
    order = user.orders.new
    order.name = cart.name
    order.build_shipping_address(cart.shipping_address.slice(:address1, :address2, :address3, :locality, :region, :postcode, :country))
    cart.line_item.order = order # TODO: save?
    order.amount = cart.amount
    order
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_order, only: [:thank_you]

  def index
    @orders = current_user.orders.includes(line_item: :product)
  end

  def new
    if current_cart.empty?
      redirect_to root_path
    else
      @cart = current_cart
      @order = Order.build_from_cart(@cart, current_user)
      @payment_method = Braintree::PaymentMethod.find(current_cart.bt_payment_method_token)
    end
  end

  def create
    @order = Order.build_from_cart(current_cart, current_user)

    if @order.save!
      session[:cart_id] = nil

      # TODO: Move to service object
      result = Braintree::Transaction.sale(
        amount: @order.amount,
        payment_method_token: current_cart.bt_payment_method_token
      )

      if result.success?
        @order.bt_transaction_id = result.transaction.id
        @order.save!

        User.notify_fulfiller!(@order)

        redirect_to thank_you_order_path(@order)
      else
        flash[:alert] = 'Unable to create a transaction'

        redirect_to root_path
      end
    else
      flash[:alert] = 'Unable to create a new order'

      render :new
    end
  end

  def thank_you
  end

  def show_acceptance
    # TODO: Move to before filter in acceptance controller
    @order = Order.find(params[:id])
    @fulfill_request = @order.fulfill_requests.find_by_token(params[:token])

    # TODO: Move if/else render login in view into view object
  end

  def update_acceptance
    # TODO: Consider resolving race condition using redis

    @order = Order.find(params[:id])
    @fulfill_request = FulfillRequest.find(params[:fulfill_request_id])

    return if @order.accepted?

    @order.fulfiller = @fulfill_request.user
    @order.save!

    # TODO: Move if/else render login in view into view object

    # TODO: Move mailing action to sidekiq
    UserMailer.notify_match_success(@order.fulfiller_id, @order).deliver_later!

    # TODO: redirect_to done_acceptance_order_path(@order)
  end

  private

  def find_order
    @order = current_user.orders.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:name, :fulfill_request, shipping_address_attributes:
                                  [:address1, :address2, :address3, :locality,
                                   :region, :postcode, :country])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_acceptance.html.erb
<div class="container section">
  <div class="page-header text-center">
    <h1>代購請求</h1>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @order.line_item.product.picture.url, class: 'center-block product-image' %>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <table class="table acceptance">
            <tr>
              <th>產品名稱</th>
              <td><%= @order.line_item.product.name %></td>
            </tr>
            <tr>
              <th>單價</th>
              <td><%= number_to_currency(@order.line_item.product.price, precision: 0) %></td>
            </tr>
            <tr>
              <th>數量</th>
              <td><%= @order.line_item.quantity %></td>
            </tr>
            <tr>
              <th>BeMine 將支付您</th>
              <td><%= number_to_currency(@order.line_item.product.price * @order.line_item.quantity, precision: 0) %></td>
            </tr>
          </table>
          <%= link_to "接受代購", update_acceptance_order_path(@order, fulfill_request_id: @fulfill_request.id), class: 'btn btn-default btn-lg btn-bemine center-block', method: :post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/_accepted.html.erb
<div class="container section">
  <div class="page-header text-center">
    <h1>代購接受！</h1>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @order.line_item.product.picture.url, class: 'center-block product-image' %>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <table class="table acceptance">
            <tr>
              <th>產品名稱</th>
              <td><%= @order.line_item.product.name %></td>
            </tr>
            <tr>
              <th>單價</th>
              <td><%= number_to_currency(@order.line_item.product.price, precision: 0) %></td>
            </tr>
            <tr>
              <th>數量</th>
              <td><%= @order.line_item.quantity %></td>
            </tr>
            <tr>
              <th>BeMine 將支付您</th>
              <td><%= number_to_currency(@order.line_item.product.price * @order.line_item.quantity, precision: 0) %></td>
            </tr>
          </table>
          <p>請將於5天內把產品寄至 BeMine 收購中心</p>
          <address>104台北市中山區南京東路二段97號、號5樓</address>
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3614.4629278888415!2d121.53007031476685!3d25.05229424371227!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442a96126c50265%3A0xf47e458e3751f344!2zMTA05Y-w5YyX5biC5Lit5bGx5Y2A5Y2X5Lqs5p2x6Lev5LqM5q61OTfomZ8!5e0!3m2!1szh-TW!2stw!4v1453995057649" width="100%" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/_rejected.html.erb
<div class="container section">
  <div class="row">
    <div class="page-header text-center">
      <%= fa_icon 'frown-o 4x' %>
      <h1>抱歉！別人已經接受這個代購請求</h1>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<h1>我的訂單一覽</h1>
<table class="table">
  <tr>
    <th>訂單編號</th>
    <th>細目</th>
    <th>總金額</th>
  </tr>
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td>
        <% line = order.line_item %>
        <%= line.product.name %>: <%= line.quantity %> 筆
    </td>
      <td>$<%= order.amount %></td>
    </tr>
  <% end %>
</table>

app/views/orders/new.html.erb
<div class="container section">
  <div class="page-header text-center">
    <h1>訂單確認</h1>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h2><%= @order.line_item.product.name %></h2>
      <%= image_tag @order.line_item.product.picture.url, class: 'center-block product-image' %>
    </div>
    <div class="col-md-6">
      <div class="col-xs-12">
        <h2 class="side-section">產品</h2>
        <p>數量 <%= @order.line_item.quantity %></p>
        <p>總價 <%= number_to_currency(@order.amount, precision: 0) %></p>
      </div>
      <div class="col-xs-12">
        <h2 class="side-section">付款</h2>
        <p><%= image_tag @payment_method.image_url %> •••• •••• •••• <%= @payment_method.last_4 %></p>
        <%= link_to '變更', show_payment_cart_path(@cart), data: { no_turbolink: true } %>
      </div>
      <div class="col-xs-12">
        <h2 class="side-section">收件資訊</h2>
        <p><%= @order.name %></p>
        <p>
          <%= @order.shipping_address.postcode %>
          <%= @order.shipping_address.region %>
          <%= @order.shipping_address.locality %>
          <%= @order.shipping_address.address1 %>
        </p>
        <p><%= ISO3166::Country.find_country_by_alpha2(@order.shipping_address.country).name %></p>
        <%= link_to '變更', show_address_cart_path(@cart) %>
      </div>
      <%= simple_form_for @order do |f| %>
        <div class=""><%= f.button :submit, '下單', class: 'btn btn-default btn-lg btn-bemine center-block' %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/show_acceptance.html.erb
<% if @order.accepted? %>
  <% if @order.fulfiller == @fulfill_request.user %>
    <%= render 'accepted' %>
  <% else %>
    <%= render 'rejected' %>
  <% end %>
<% else %>
  <%= render 'acceptance' %>
<% end %>

app/views/orders/thank_you.html.erb
<div class="container section">
  <div class="page-header text-center">
    <h2>訂單內容</h2>
  </div>
  <div class="row">
    <div class="col-md-6">
      <table class="table">
        <tr>
          <th class="table-header">產品</th>
          <td>
            <%= image_tag @order.line_item.product.picture.url, class: 'product-image-small' %>
            <p><%= @order.line_item.product.name %></p>
          </td>
        </tr>
        <tr>
          <th class="table-header">小計</th>
          <td><%= number_to_currency(@order.amount, precision: 0) %></td>
        </tr>
        <tr>
          <th class="table-header">運費</th>
          <td class="table-header">免費</td>
        </tr>
        <tr>
          <th class="table-header">總價</th>
          <td><%= number_to_currency(@order.amount, precision: 0) %></td>
        </tr>
        <tr>
          <th class="table-header">寄件地址</th>
          <td>
            <%= @order.shipping_address.postcode %>
            <%= @order.shipping_address.region %>
            <%= @order.shipping_address.locality %>
            <%= @order.shipping_address.address1 %>
          </td>
        </tr>
      </table>
    </div>
    <div class="col-md-6">
      <%= image_tag "thankyou.png", class: 'center-block padding' %>
      <p class="padding">親愛的 <%= @order.name %> 您好，謝謝您使用 <%= @order.line_item.product.name %> 商品的媒合服務,我們將在24小時內Email通知您媒合結果，在此期間我們不會收取您任何費用，請您放心。</p>
      <%= link_to '繼續 Shopping', root_path, :class => "btn btn-default btn-lg btn-continue-shopping center-block padding" %>
    </div>
  </div>
</div>

app/views/orders/update_acceptance.html.erb
<% if @order.fulfiller == @fulfill_request.user %>
  <%= render 'accepted' %>
<% else %>
  <%= render 'rejected' %>
<% end %>