config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  resources :categories

  resources :products do
    member do
      post :buy
      post :cancel
    end
  end

  resources :carts do
    member do
      get  :show_address
      post :update_address
      get  :show_payment
      post :update_payment
    end
  end

  resources :orders do
    member do
      get :thank_you
      get :show_acceptance
      post :update_acceptance
    end
  end

  Bemine::Application.routes.draw do
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new( category_params )

    if @category.save
      flash[:notice] = '新增成功'
      redirect_to categories_path
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end

  private

  def category_params
    params.require(:category).permit(:name, :description, :location, :price, :picture )
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="https://jessicafaulkner.com/wp-content/uploads/2015/07/HAPPENING_IN_LOS_ANGELES_JESSICA_FAULKNER_72715_2.jpg" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="http://3mkfmvpr88h3off9du3hk812.wpengine.netdna-cdn.com/wp-content/uploads/2015/02/Dollarphotoclub_73314409-1600x600_c.jpg" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="https://www.qvestmedia.com/fileadmin/_processed_/csm_qm-location-singapore-tphd_97f60e792d.jpg" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="https://www.strath.ac.uk/media/1newwebsite/images-general/internationalstudentssection/countrypages/italy-1600x600.jpg" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="http://korenbrothers.com/wp-content/uploads/2014/10/KB00001075301.jpg" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div id="top" class = "topwords" ><img src = "http://www.churchhousecollection.com/resources/123%20clip%20art.jpg" alt="..."></div>
<% @categories.each do |c|%>
  <%=link_to image_tag( c.picture.url ), category_path(c)%>
<% end %>
<%= link_to "Add new category", new_category_path, :class => "btn btn-info"%>

app/views/categories/new.html.erb
<%= form_for @category, :url => categories_path do |f| %>
  <%= f.label :name, "Category Name"%>
  <div class= "form group">
    <%= f.text_field :name%>
  </div>
  <%= f.label :picture, "Category Picture" %>
  <%= f.file_field :picture %>
  <div class= "form group">
    <%= f.submit "送出", :class => "btn btn-warning"%>
  </div>
<% end %>

app/views/categories/show.html.erb
<div class="container section">
  <div class="page-header text-center">
    <h1><%= @category.name %></h1>
  </div>
  <div id="masonry-container" class="transitions-enabled infinite-scroll centered clearfix">
    <% @products.each do |p| %>
      <div class="box col3">
        <%= link_to product_path(p) do %>
          <%= image_tag(p.picture.url) %>
        <% end %>
        <div class="h3"><%= p.name %></div>
        <div class="h4"><%= p.location %></div>
        <div class="h4"><%= number_to_currency(p.price, precision: 0) %></div>
        <% if current_user && current_user.admin? %>
          <%= link_to "商品detail", product_path(p), :class => "btn btn-info" %>
          <%= link_to "更改商品內容", edit_product_path(p), :class => "btn btn-info" %>
          <%= link_to "刪除", product_path(p), :method => :delete, :data =>{ :confirm => "Are u sure?" }, :class => "btn btn-danger" %>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if current_user && current_user.admin? %>
    <%= link_to "新增", new_product_path, :class => "btn btn-info" %>
  <% end %>
</div>