config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  resources :categories

  resources :products do
    member do
      post :buy
      post :cancel
    end
  end

  resources :carts do
    member do
      get  :show_address
      post :update_address
      get  :show_payment
      post :update_payment
    end
  end

  resources :orders do
    member do
      get :thank_you
      get :show_acceptance
      post :update_acceptance
    end
  end

  Bemine::Application.routes.draw do
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  validates_presence_of :name, :price

  belongs_to :category
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :new_product, only: [:new]
  before_action :find_product, only: [:show, :edit, :update, :destroy, :buy, :cancel, :match]

  def index
    @products = Product.all
  end

  def new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = '新增成功'
      redirect_to products_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)


      flash[:notice] = '編輯成功'
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product.delete

    flash[:alert] = '刪除成功'
    redirect_to products_path
  end

  def buy
    quantity = params[:quantity].to_i

    # Update line item in cart
    # extract = current_cart.add(product, quantity)
    if current_cart.line_item
      current_cart.line_item.update!(product: @product, quantity: quantity)
    else
      current_cart.create_line_item!(cart: current_cart, product: @product, quantity: quantity)
    end

    respond_to do |format|
      format.html { redirect_to show_address_cart_path(current_cart), notice: '加入成功' }
      format.js
    end
  end

  def cancel
    current_cart.line_item.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: '移除成功' }
      format.js { render :buy }
    end
  end

  private

  def new_product
    @product = Product.new
  end

  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :location, :price, :picture, :matcharea, :category_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_cart.html.erb
<div class="cart">
  <% if line = current_cart.line_item %>
    <h2><%= line.product.name %></h2>
    <%= image_tag line.product.picture.url, class: 'center-block product-image' %>
  <% end %>
</div>

app/views/products/_list.html.erb
<div id="masonry-container" class="transitions-enabled infinite-scroll centered clearfix">
  <% @products.each do |p| %>
    <div class="box col3">
      <%= link_to product_path(p) do %>
        <%= image_tag(p.picture.url) %>
      <% end %>
      <div class="h3"><%= p.name %></div>
      <div class="h4"><%= p.location %></div>
      <div class="h4"><%= number_to_currency(p.price, precision: 0) %></div>
      <% if current_user && current_user.admin? %>
        <%= link_to "商品detail", product_path(p), :class => "btn btn-info" %>
        <%= link_to "更改商品內容", edit_product_path(p), :class => "btn btn-info" %>
        <%= link_to "刪除", product_path(p), :method => :delete, :data =>{ :confirm => "Are u sure?" }, :class => "btn btn-danger" %>
      <% end %>
    </div>
  <% end %>
</div>
<% if current_user && current_user.admin? %>
  <%= link_to "新增", new_product_path, :class => "btn btn-info" %>
<% end %>
</div>

app/views/products/edit.html.erb
<%= form_for @product, :url => product_path(@product), :method => :patch do |f| %>
  <%= f.label :name, "Product Name" %>
  <div class="form-group">
    <%= f.text_field :name%>
  </div>
  <%= f.label :description, "Product Description" %>
  <div class="form-group">
    <%= f.text_area :description%>
  </div>
  <%= f.label :location, "Product Location" %>
  <div class="form-group">
    <%= f.text_field :location%>
  </div>
  <%= f.label :price, "Price" %>
  <div class="form-group">
    <%= f.text_field :price%>
  </div>
  <%= f.label :matcharea, "match 訊息" %>
  <div class="form-group">
    <%= f.text_field :matcharea%>
  </div>
  <div class="form-group">
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="form-group">
    <%= f.submit "送出", :class => "btn btn-warning" %>
  </div>
<% end %>

app/views/products/index.html.erb
<div class="bbcontainer">
  <div class="category">
    <div class="aacontainer">
      <div class="category">
        <div id="masonry-container" class="transitions-enabled infinite-scroll centered clearfix">
          <% @products.each do |p| %>
            <div class="box col3">
              <div class = "pics"><%=link_to image_tag(p.picture.url), p %></div>
              <div class = "proname"><%= p.name %></div>
              <div class="prolocate"><%= p.location %></div>
              <div class="proprice"><%= number_to_currency(p.price, precision: 0) %></div>
              <div class="bttn"><%= link_to "商品detail", p, :class => "btn btn-info" %></div>
              <div class="bttn"><%= link_to "更改商品內容", edit_product_path(p), :class => "btn btn-info" %></div>
              <div class="btttn"><%= link_to "刪除", p, :method => :delete, :data =>{ :confirm => "Are u sure?" }, :class => "btn btn-danger" %></div>
            </div>
          <% end %>
        </div>
        <%= link_to "New Product", new_product_path, :class => "btn btn-info" %>
      </div>
    </div>
  </div>
</div>

app/views/products/match.html.erb
<h1>123123</h1>

app/views/products/new.html.erb
<%= form_for @product, :url => products_path do  |f| %>
  <%= f.label :name, "Product Name"%>
  <div class= "form group">
    <%= f.text_field :name%>
  </div>
  <%= f.label :description, "Product Description"%>
  <div class= "form group">
    <%= f.text_area :description%>
  </div>
  <%= f.label :location, "Product Location"%>
  <div class= "form group">
    <%= f.text_field :location%>
  </div>
  <%= f.label :price, "Price"%>
  <div class= "form group">
    <%= f.text_field :price%>
  </div>
  <%= f.label :picture, "Product Picture" %>
  <%= f.file_field :picture %>
  <%= f.label :matcharea, "match 訊息"%>
  <div class= "form group">
    <%= f.text_field :matcharea%>
  </div>
  <div class="form-group">
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class= "form group">
    <%= f.submit "送出", :class => "btn btn-warning"%>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="container section">
  <div class="page-header text-center">
    <h1><%= @product.name %></h1>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @product.picture.url, class: 'center-block product-image' %>
    </div>
    <div class="col-md-6">
      <p><%= @product.description %></p>
      <h3><%= number_to_currency(@product.price, precision: 0) %></h3>
      <div class="buy-container">
        <div class="panel panel-default">
          <div class="panel-body">
            <%= simple_form_for @product, url: buy_product_path(@product), method: :post, html: { class: 'form-horizontal'} do %>
              <div class="form-group">
                <%= label_tag :quantity, '數量', class: 'col-xs-3 control-label' %>
                <div class="col-xs-9">
                  <%= select_tag :quantity, options_for_select(1..5), :class => 'form-control col-xs-10' %>
                </div>
              </div>
              <div class="form-group">
                <%= submit_tag '訂購', :class => 'btn btn-default btn-lg btn-bemine center-block' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>