config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  resources :categories

  resources :products do
    member do
      post :buy
      post :cancel
    end
  end

  resources :carts do
    member do
      get  :show_address
      post :update_address
      get  :show_payment
      post :update_payment
    end
  end

  resources :orders do
    member do
      get :thank_you
      get :show_acceptance
      post :update_acceptance
    end
  end

  Bemine::Application.routes.draw do
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeMine - 海外代購媒合</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= yield :stylesheet %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="header clearfix">
      <div class="logo">
        <p><%=link_to image_tag("logo.png"), root_path %></p>
      </div>
      <div class="menu">
        <ul>
          <% if current_user %>
            <li id="user-name"><%= current_user.name %></li>
            <li><%= link_to('登出', destroy_user_session_path, :method => :delete, :class => "btn btn-menu") %></li>
            <!--   <li><%= link_to('修改密碼', edit_registration_path(:user), :class => "btn btn-menu") %></li> -->
            <li><%= link_to('訂單', orders_path, :class => "btn btn-menu") %></li>
          <% else %>
            <li><%= link_to('註冊', new_registration_path(:user), :class => "btn btn-signup") %></li>
            <li><%= link_to('登入', new_session_path(:user), :class => "btn btn-menu") %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <%= yield %>
    <div class="footer">
      <p class="text-center">© BeMine</p>
    </div>
  </body>
</html>